<?php

// try to find my libemail script
$libemail='none';

// look in home

$home = getenv("HOME");
if ((!$home) || ($home == '')) {
    if (is_dir('/home/logicuma')) {
        $home = '/home/logicuma';
    } else {
        if (is_dir('/home/kck')) {
            $home = '/home/kck/';
        }
    }
}

if (file_exists("$home/bin/kckmail/libemail.php")) {
    $libemail = "$home/bin/kckmail/libemail.php";
}

// look up several subfolders
if ($libemail === "none") {
    $trynext = dirname(___FILE___) . '/../../../bin/kckmail/libemail.php';
    if (file_exists($trynext)) {
        $libemail = realpath ($trynext);
    }
}

// return if not found
if ($libemail === 'none') {
    return false;
}

// require it
require_once($libemail);

// define the function we need
function custom_send_email($to, $subject, $html) {
    $html .= "\r\n<p></p><p style=\"font-size: 80%; font-style: italic;\">" .
        "\r\n<strong>Please note</strong>: " . 
        "\r\nThis email was auto-generated by the JHAP typesetting framework " .
        "\r\nand not written directly by me personally. " .
        "\r\nBut a reply should still reach me, and if needed, I can pass " .
        "\r\nalong a message to the appropriate people! –Kevin</p>\r\n";
    return html2multi($to, $subject, $html, [], [], [], false);
}

